project_id = "pmrhezgnyffiskbaiudb"

[functions.retrain-model]
verify_jwt = true

[functions.ai-translate]
verify_jwt = false

[functions.analyze-phrase-quality]
verify_jwt = true

[functions.train-translation-model]
verify_jwt = true

[functions.enhance-training-data]
verify_jwt = false

[functions.bulk-validate-phrases]
verify_jwt = false

[functions.suggest-dictionary-fix]
verify_jwt = true

[functions.enrich-training-data]
verify_jwt = true