services:
  react-app-bariba:
    image: nginx:alpine
    container_name: react-app-bariba-js
    restart: always
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.react-app-bariba.rule=Host(`fitila.bj`)"
      - "traefik.http.routers.react-app-bariba.entrypoints=websecure"
      - "traefik.http.routers.react-app-bariba.tls.certresolver=myresolver"
      - "traefik.http.services.react-app-bariba.loadbalancer.server.port=80"
      - "traefik.port=80"
    ports:
      - 8085:80
    networks:
      - web

networks:
  web:
    external: true
